name: BobApp-Backend CI/CD pipeline

on: [push, pull_request]

env:
  BACKEND_PATH: 'back'
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'temurin'
  CACHE_MAVEN: 'maven'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.BACKEND_PATH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.CACHE_MAVEN }}

      - name: Build with Maven
        working-directory: ${{ env.BACKEND_PATH }}
        run: mvn -B clean compile

  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.BACKEND_PATH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.CACHE_MAVEN }}

      - name: Run tests with Maven
        working-directory: ${{ env.BACKEND_PATH }}
        run: mvn -B clean verify

      - name: Publish tests report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Back-end Tests
          working-directory: ${{ env.BACKEND_PATH }}
          path: target/surefire-reports/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: java-junit


  quality-backend:
    needs: test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.BACKEND_PATH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.CACHE_MAVEN }}

      - name: Sonar Quality Scan
        working-directory: ${{ env.BACKEND_PATH }}
        run: |
          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.organization=maximedrouault \
            -Dsonar.projectKey=maximedrouault_bobapp-back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}


  docker:
    needs: quality-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.BACKEND_PATH }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_BACK }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BACKEND_PATH }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest